"use client";

import Link from "next/link";
import { CircleAlert, FileText, Plus, ReceiptText, X } from "lucide-react";
import { useMemo, useState, useTransition } from "react";
import type { BillingData } from "@/lib/facturacion";
import type { Sale } from "@/lib/ventas";
import { crearBorradorFactura } from "./actions";

const money = (n: number) => new Intl.NumberFormat("es-EC", { style: "currency", currency: "USD" }).format(Number(n));

export default function BillingBoard(props: BillingData) {
  const preview = props.status === "setup_required";
  const [selected, setSelected] = useState<Sale | null>(null); const [notice, setNotice] = useState(props.message ?? ""); const [pending, start] = useTransition();
  const draftedIds = useMemo(() => new Set(props.drafts.filter((d) => d.estado !== "anulada").map((d) => d.venta_id)), [props.drafts]);
  const eligible = props.sales.filter((sale) => sale.estado === "completada" && !draftedIds.has(sale.id));
  if (props.status !== "ready" && !preview) return <main className="page agenda-page"><div className="container agenda-shell"><header className="agenda-header"><div><Link className="back-link" href="/">← LUMOS</Link><p className="eyebrow">FACTURACIÓN</p><h1>Facturas</h1><p className="subtitle">{props.message}</p></div></header><div className="notice"><CircleAlert size={18} /><span>Los recibos de venta siguen disponibles. Este módulo no emitirá al SRI hasta configurar certificado y establecimiento.</span></div></div></main>;
  const customerName = (sale: Sale) => { const patient = props.patients.find((p) => p.id === sale.paciente_id); return patient ? `${patient.nombres} ${patient.apellidos}` : sale.cliente_nombre || "Consumidor final"; };
  const submit = (form: HTMLFormElement) => start(async () => { try { await crearBorradorFactura(new FormData(form)); setNotice("Borrador creado. Aún no ha sido enviado al SRI."); setSelected(null); } catch (error) { setNotice(error instanceof Error ? error.message : "No se pudo crear el borrador."); } });
  return <main className="page agenda-page"><div className="container agenda-shell">
    <header className="agenda-header"><div><Link className="back-link" href="/">← LUMOS</Link><p className="eyebrow">ADMINISTRACIÓN</p><h1>Facturación</h1><p className="subtitle">Prepara facturas desde ventas cerradas y conserva su trazabilidad.</p></div></header>
    <div className="notice"><CircleAlert size={18} /><span>{notice || "Modo borrador: ningún documento se envía al SRI todavía."}</span></div>
    <section className="agenda-summary"><article><FileText size={21} /><strong>{props.drafts.length}</strong><span>borradores creados</span></article><article><ReceiptText size={21} /><strong>{eligible.length}</strong><span>ventas listas para preparar</span></article></section>
    <section className="glass agenda-board" style={{ marginBottom: 18 }}><p className="section-label">VENTAS SIN BORRADOR</p><h2>Preparar factura</h2>{eligible.length ? <div className="task-list">{eligible.map((sale) => <article className="task-card" key={sale.id}><div className="task-main"><div className="task-meta"><span>{props.branches.find((b) => b.id === sale.sucursal_id)?.nombre ?? "Sin sucursal"}</span><span>{new Date(sale.creado_en).toLocaleDateString("es-EC")}</span></div><h2>{customerName(sale)}</h2><p>{sale.venta_items.map((item) => item.descripcion).join(", ")}</p></div><div className="task-actions"><strong>{money(sale.total)}</strong><button disabled={preview} title={preview ? "Disponible después de activar la migración" : undefined} onClick={() => setSelected(sale)}><Plus size={14} /> {preview ? "Pendiente activar" : "Crear borrador"}</button></div></article>)}</div> : <p className="field-hint">No hay ventas pendientes de preparar.</p>}</section>
    <section className="glass agenda-board"><p className="section-label">DOCUMENTOS PREPARADOS</p><h2>Borradores internos</h2>{props.drafts.length ? <div className="task-list">{props.drafts.map((draft) => <article className="task-card" key={draft.id}><div className="task-main"><div className="task-meta"><span>Borrador #{draft.numero_interno}</span><span>{new Date(draft.creado_en).toLocaleDateString("es-EC")}</span></div><h2>{draft.cliente_nombre}</h2><p>{draft.cliente_identificacion || "Sin identificación"}</p></div><div className="task-actions"><span className="state-pill">{draft.estado.replaceAll("_", " ")}</span><strong>{money(draft.total)}</strong></div></article>)}</div> : <p className="field-hint">Todavía no hay borradores.</p>}</section>
    {selected && <div className="modal-backdrop"><section className="new-patient-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={() => setSelected(null)} aria-label="Cerrar"><X size={19} /></button><p className="section-label">BORRADOR DE FACTURA</p><h2>{customerName(selected)}</h2><p>Total de venta: <strong>{money(selected.total)}</strong>. Confirma los datos del comprador.</p><form onSubmit={(e) => { e.preventDefault(); submit(e.currentTarget); }}><input type="hidden" name="venta_id" value={selected.id} /><div className="new-patient-form"><label>Identificación / RUC<input name="cliente_identificacion" defaultValue={props.patients.find((p) => p.id === selected.paciente_id)?.cedula ?? ""} required /></label><label>Correo<input name="cliente_email" type="email" /></label><label className="task-description">Dirección<input name="cliente_direccion" /></label></div><p className="field-hint">Este paso solo guarda un borrador. La firma electrónica, impuestos, secuencial y autorización SRI se configurarán en un bloque posterior.</p><div className="modal-actions"><button type="button" className="outline-action" onClick={() => setSelected(null)}>Cancelar</button><button className="new-consultation" disabled={pending}>{pending ? "Guardando…" : "Guardar borrador"}</button></div></form></section></div>}
  </div></main>;
}
