"use client";
import { paymentMethods } from "@/lib/payment-methods";

import Link from "next/link";
import { CircleAlert, LockKeyhole, Plus, Wallet, X } from "lucide-react";
import { useMemo, useState, useTransition } from "react";
import type { BusinessDebt, PrivateAdminData } from "@/lib/mi-espacio";
import { crearDeuda, registrarPagoDeuda } from "./actions";

const money = (n: number) => new Intl.NumberFormat("es-EC", { style: "currency", currency: "USD" }).format(Number(n));
const today = () => new Date().toISOString().slice(0, 10);

export default function PrivateAdminBoard(props: PrivateAdminData) {
  const preview = props.status === "setup_required";
  const [month, setMonth] = useState(today().slice(0, 7)); const [showNew, setShowNew] = useState(false); const [paying, setPaying] = useState<BusinessDebt | null>(null); const [notice, setNotice] = useState(props.message ?? ""); const [pending, start] = useTransition();
  const monthDebts = useMemo(() => props.debts.filter((debt) => (debt.fecha_vencimiento || debt.fecha_deuda).startsWith(month)), [props.debts, month]);
  const pendingTotal = monthDebts.filter((d) => d.estado === "pendiente").reduce((sum, d) => sum + Number(d.saldo), 0);
  if (props.status !== "ready" && !preview) return <main className="page agenda-page"><div className="container agenda-shell"><header className="agenda-header"><div><Link className="back-link" href="/">← LUMOS</Link><p className="eyebrow">ESPACIO PRIVADO</p><h1>Deudas de la óptica</h1><p className="subtitle">{props.message}</p></div></header><div className="notice"><LockKeyhole size={18} /><span>Este apartado no comparte datos con las cuentas de pacientes.</span></div></div></main>;
  const submit = (form: HTMLFormElement, action: (data: FormData) => Promise<void>, done: () => void, ok: string) => start(async () => { try { await action(new FormData(form)); setNotice(ok); done(); } catch (error) { setNotice(error instanceof Error ? error.message : "No se pudo guardar."); } });
  return <main className="page agenda-page"><div className="container agenda-shell">
    <header className="agenda-header"><div><Link className="back-link" href="/">← LUMOS</Link><p className="eyebrow">ESPACIO PRIVADO · SUPERADMIN</p><h1>Deudas de la óptica</h1><p className="subtitle">Control mensual por sucursal, separado de los saldos de pacientes.</p></div><button className="new-task" disabled={preview} title={preview ? "Disponible después de activar la migración" : undefined} onClick={() => setShowNew(true)}><Plus size={17} /> {preview ? "Vista previa" : "Nueva deuda"}</button></header>
    <div className="notice"><LockKeyhole size={18} /><span>{notice || "Solo tu cuenta de superadmin puede leer o modificar este apartado."}</span></div>
    <div className="new-patient-form" style={{ maxWidth: 220, marginBottom: 14 }}><label>Mes a revisar<input type="month" value={month} onChange={(e) => setMonth(e.target.value)} /></label></div>
    <section className="agenda-summary"><article><Wallet size={21} /><strong>{money(pendingTotal)}</strong><span>pendiente en el mes</span></article><article><CircleAlert size={21} /><strong>{monthDebts.filter((d) => d.estado === "pendiente").length}</strong><span>deudas abiertas</span></article></section>
    <section className="glass agenda-board"><p className="section-label">CONTROL MENSUAL</p><h2>Obligaciones por sucursal</h2>{monthDebts.length ? <div className="task-list">{monthDebts.map((debt) => <article className="task-card" key={debt.id}><div className="task-main"><div className="task-meta"><span>{props.branches.find((b) => b.id === debt.sucursal_id)?.nombre ?? "Sin sucursal"}</span><span>{debt.frecuencia === "mensual" ? "Mensual" : "Una vez"}</span></div><h2>{debt.proveedor}</h2><p>{debt.concepto}</p><p className="field-hint">Vence: {debt.fecha_vencimiento || "sin fecha"} · Original {money(debt.monto_original)}</p></div><div className="task-actions"><span className={`state-pill ${debt.estado === "pagada" ? "aprobada" : ""}`}>{debt.estado}</span><strong>{money(debt.saldo)}</strong>{debt.estado === "pendiente" && <button onClick={() => setPaying(debt)}>Registrar abono</button>}</div></article>)}</div> : <p className="field-hint">No hay deudas registradas para este mes.</p>}</section>
    {showNew && <div className="modal-backdrop"><section className="new-patient-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={() => setShowNew(false)} aria-label="Cerrar"><X size={19} /></button><p className="section-label">NUEVA OBLIGACIÓN</p><h2>Registrar deuda</h2><form onSubmit={(e) => { e.preventDefault(); submit(e.currentTarget, crearDeuda, () => setShowNew(false), "Deuda registrada."); }}><DebtForm companies={props.companies} branches={props.branches} /><div className="modal-actions"><button type="button" className="outline-action" onClick={() => setShowNew(false)}>Cancelar</button><button className="new-consultation" disabled={pending}>Guardar deuda</button></div></form></section></div>}
    {paying && <div className="modal-backdrop"><section className="new-patient-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={() => setPaying(null)} aria-label="Cerrar"><X size={19} /></button><p className="section-label">ABONO PRIVADO</p><h2>{paying.proveedor}</h2><p>Saldo actual: <strong>{money(paying.saldo)}</strong></p><form onSubmit={(e) => { e.preventDefault(); submit(e.currentTarget, registrarPagoDeuda, () => setPaying(null), "Abono registrado."); }}><input type="hidden" name="deuda_id" value={paying.id} /><div className="new-patient-form"><label>Monto<input name="monto" type="number" min="0.01" max={paying.saldo} step="0.01" required /></label><label>Fecha<input name="fecha_pago" type="date" defaultValue={today()} required /></label><label>Método<select name="metodo" defaultValue="transferencia">{paymentMethods.map((method) => <option key={method.value} value={method.value}>{method.label}</option>)}</select></label><label>Referencia<input name="referencia" /></label></div><div className="modal-actions"><button type="button" className="outline-action" onClick={() => setPaying(null)}>Cancelar</button><button className="new-consultation" disabled={pending}>Guardar abono</button></div></form></section></div>}
  </div></main>;
}

function DebtForm({ companies, branches }: { companies: PrivateAdminData["companies"]; branches: PrivateAdminData["branches"] }) {
  const [companyId, setCompanyId] = useState(companies[0]?.id ?? ""); const available = branches.filter((b) => b.empresa_id === companyId);
  return <div className="new-patient-form"><label>Empresa<select name="empresa_id" value={companyId} onChange={(e) => setCompanyId(e.target.value)}>{companies.map((c) => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label>Sucursal<select name="sucursal_id" required defaultValue=""><option value="" disabled>Selecciona</option>{available.map((b) => <option key={b.id} value={b.id}>{b.nombre}</option>)}</select></label><label>Proveedor<input name="proveedor" required /></label><label>Concepto<input name="concepto" required /></label><label>Monto USD<input name="monto" type="number" min="0.01" step="0.01" required /></label><label>Fecha de deuda<input name="fecha_deuda" type="date" defaultValue={today()} /></label><label>Vencimiento<input name="fecha_vencimiento" type="date" /></label><label>Frecuencia<select name="frecuencia"><option value="unica">Una vez</option><option value="mensual">Mensual</option></select></label><label className="task-description">Notas<textarea name="notas" /></label></div>;
}
