-- Bloque local: facturación en borrador y deudas privadas de la administración.
-- Esta migración se prepara en el código, pero no debe aplicarse a producción
-- hasta que la propietaria autorice expresamente el cambio.

create table if not exists public.facturas_borrador (
  id uuid primary key default gen_random_uuid(),
  venta_id uuid references public.ventas(id) on delete set null,
  empresa_id uuid not null references public.empresas(id),
  sucursal_id uuid references public.sucursales(id),
  cliente_nombre text not null,
  cliente_identificacion text,
  cliente_email text,
  cliente_direccion text,
  numero_interno bigint generated by default as identity,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  descuento numeric(12,2) not null default 0 check (descuento >= 0),
  iva numeric(12,2) not null default 0 check (iva >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  items jsonb not null default '[]'::jsonb check (jsonb_typeof(items) = 'array'),
  estado text not null default 'borrador' check (estado in ('borrador', 'lista_para_emitir', 'autorizada', 'rechazada', 'anulada')),
  clave_acceso text,
  numero_autorizacion text,
  notas text,
  created_by uuid not null references public.usuarios(id),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create unique index if not exists facturas_borrador_venta_unica
  on public.facturas_borrador (venta_id)
  where venta_id is not null and estado <> 'anulada';
create index if not exists facturas_borrador_empresa_fecha
  on public.facturas_borrador (empresa_id, creado_en desc);

create table if not exists public.deudas_negocio (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id),
  sucursal_id uuid references public.sucursales(id),
  proveedor text not null,
  concepto text not null,
  monto_original numeric(12,2) not null check (monto_original > 0),
  saldo numeric(12,2) not null check (saldo >= 0),
  fecha_deuda date not null default current_date,
  fecha_vencimiento date,
  frecuencia text not null default 'unica' check (frecuencia in ('unica', 'mensual')),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'pagada', 'anulada')),
  notas text,
  created_by uuid not null references public.usuarios(id),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.pagos_deuda_negocio (
  id uuid primary key default gen_random_uuid(),
  deuda_id uuid not null references public.deudas_negocio(id) on delete cascade,
  monto numeric(12,2) not null check (monto > 0),
  fecha_pago date not null default current_date,
  metodo text not null default 'transferencia' check (metodo in ('efectivo', 'transferencia', 'tarjeta', 'otro')),
  referencia text,
  notas text,
  created_by uuid not null references public.usuarios(id),
  creado_en timestamptz not null default now()
);

create index if not exists deudas_negocio_sucursal_vencimiento
  on public.deudas_negocio (sucursal_id, fecha_vencimiento);
create index if not exists pagos_deuda_negocio_deuda_fecha
  on public.pagos_deuda_negocio (deuda_id, fecha_pago desc);

alter table public.facturas_borrador enable row level security;
alter table public.deudas_negocio enable row level security;
alter table public.pagos_deuda_negocio enable row level security;

grant select, insert, update on public.facturas_borrador to authenticated;
grant usage, select on sequence public.facturas_borrador_numero_interno_seq to authenticated;
grant select, insert, update on public.deudas_negocio to authenticated;
grant select, insert on public.pagos_deuda_negocio to authenticated;

create policy "facturas visibles para administracion de su empresa"
on public.facturas_borrador for select to authenticated
using (
  public.es_superadmin()
  or exists (
    select 1
    from public.usuarios u
    join public.roles r on r.id = u.rol_id
    where u.auth_user_id = auth.uid()
      and u.activo = true
      and r.nombre in ('admin_sucursal', 'caja')
      and u.empresa_id = facturas_borrador.empresa_id
      and (u.sucursal_id is null or u.sucursal_id = facturas_borrador.sucursal_id)
  )
);

create policy "facturas creadas por administracion autorizada"
on public.facturas_borrador for insert to authenticated
with check (
  created_by = (select u.id from public.usuarios u where u.auth_user_id = auth.uid() and u.activo = true limit 1)
  and (
    public.es_superadmin()
    or exists (
      select 1
      from public.usuarios u
      join public.roles r on r.id = u.rol_id
      where u.auth_user_id = auth.uid()
        and u.activo = true
        and r.nombre in ('admin_sucursal', 'caja')
        and u.empresa_id = facturas_borrador.empresa_id
        and (u.sucursal_id is null or u.sucursal_id = facturas_borrador.sucursal_id)
    )
  )
);

create policy "facturas actualizadas por administracion autorizada"
on public.facturas_borrador for update to authenticated
using (
  public.es_superadmin()
  or exists (
    select 1
    from public.usuarios u
    join public.roles r on r.id = u.rol_id
    where u.auth_user_id = auth.uid()
      and u.activo = true
      and r.nombre in ('admin_sucursal', 'caja')
      and u.empresa_id = facturas_borrador.empresa_id
      and (u.sucursal_id is null or u.sucursal_id = facturas_borrador.sucursal_id)
  )
)
with check (
  public.es_superadmin()
  or exists (
    select 1
    from public.usuarios u
    join public.roles r on r.id = u.rol_id
    where u.auth_user_id = auth.uid()
      and u.activo = true
      and r.nombre in ('admin_sucursal', 'caja')
      and u.empresa_id = facturas_borrador.empresa_id
      and (u.sucursal_id is null or u.sucursal_id = facturas_borrador.sucursal_id)
  )
);

create policy "solo superadmin ve deudas privadas"
on public.deudas_negocio for select to authenticated
using (public.es_superadmin());
create policy "solo superadmin crea deudas privadas"
on public.deudas_negocio for insert to authenticated
with check (public.es_superadmin() and created_by = (select u.id from public.usuarios u where u.auth_user_id = auth.uid() and u.activo = true limit 1));
create policy "solo superadmin actualiza deudas privadas"
on public.deudas_negocio for update to authenticated
using (public.es_superadmin()) with check (public.es_superadmin());

create policy "solo superadmin ve pagos privados"
on public.pagos_deuda_negocio for select to authenticated
using (public.es_superadmin());
create policy "solo superadmin crea pagos privados"
on public.pagos_deuda_negocio for insert to authenticated
with check (public.es_superadmin() and created_by = (select u.id from public.usuarios u where u.auth_user_id = auth.uid() and u.activo = true limit 1));

create or replace function public.registrar_pago_deuda_negocio(
  p_deuda uuid,
  p_monto numeric,
  p_fecha date,
  p_metodo text,
  p_referencia text default null,
  p_notas text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usuario uuid;
  v_saldo numeric;
  v_pago uuid;
begin
  if not public.es_superadmin() then
    raise exception 'Acceso restringido a la administración general';
  end if;
  if p_monto is null or p_monto <= 0 then
    raise exception 'El monto debe ser mayor que cero';
  end if;
  if p_metodo not in ('efectivo', 'transferencia', 'tarjeta', 'otro') then
    raise exception 'Método de pago inválido';
  end if;

  select id into v_usuario
  from public.usuarios
  where auth_user_id = auth.uid() and activo = true
  limit 1;

  select saldo into v_saldo
  from public.deudas_negocio
  where id = p_deuda and estado = 'pendiente'
  for update;

  if v_saldo is null then raise exception 'La deuda no está disponible'; end if;
  if p_monto > v_saldo then raise exception 'El pago supera el saldo pendiente'; end if;

  insert into public.pagos_deuda_negocio (deuda_id, monto, fecha_pago, metodo, referencia, notas, created_by)
  values (p_deuda, p_monto, coalesce(p_fecha, current_date), p_metodo, nullif(trim(p_referencia), ''), nullif(trim(p_notas), ''), v_usuario)
  returning id into v_pago;

  update public.deudas_negocio
  set saldo = saldo - p_monto,
      estado = case when saldo - p_monto = 0 then 'pagada' else 'pendiente' end,
      actualizado_en = now()
  where id = p_deuda;

  return v_pago;
end;
$$;

revoke all on function public.registrar_pago_deuda_negocio(uuid, numeric, date, text, text, text) from public;
grant execute on function public.registrar_pago_deuda_negocio(uuid, numeric, date, text, text, text) to authenticated;
